[package]
name = "pallet-contracts"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for WASM contracts"
readme = "README.md"
include = ["src/**/*", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bitflags = "1.3"
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
wasm-instrument = { version = "0.4", default-features = false }
serde = { version = "1", optional = true, features = ["derive"] }
smallvec = { version = "1", default-features = false, features = [
	"const_generics",
] }
wasmi = { version = "0.20", default-features = false }
wasmparser = { package = "wasmparser-nostd", version = "0.91", default-features = false }
impl-trait-for-tuples = "0.2"

# Only used in benchmarking to generate random contract code
rand = { version = "0.8", optional = true, default-features = false }
rand_pcg = { version = "0.3", optional = true }

# Substrate Dependencies
frame-benchmarking = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false, optional = true }
frame-support = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
frame-system = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
pallet-contracts-primitives = { version = "7.0.0", default-features = false, path = "primitives" }
pallet-contracts-proc-macro = { version = "4.0.0-dev", path = "proc-macro" }
sp-api = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-core = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-io = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-runtime = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-std = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }

[dev-dependencies]
array-bytes = "4.1"
assert_matches = "1"
env_logger = "0.9"
pretty_assertions = "1"
wat = "1"

# Substrate Dependencies
pallet-balances = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
pallet-timestamp = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
pallet-insecure-randomness-collective-flip = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
pallet-utility = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-keystore = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"wasm-instrument/std",
	"wasmi/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-proc-macro/full",
	"log/std",
	"rand/std",
	"wasmparser/std",
	"pallet-balances/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"rand",
	"rand_pcg",
]
try-runtime = ["frame-support/try-runtime"]
